const FETCH_LIST_REQUEST='FETCH_LIST_REQUEST'
const FETCH_LIST='FETCH_LIST'
const FETCH_ERROR='FETCH_ERROR'
const FETCH_LIST_PASS='FETCH_LIST_PASS'
//BORROWERS DATA
const FETCH_BORROWERS_REQUEST='FETCH_BORROWERS_REQUEST'
const FETCH_BORROWERS_LIST='FETCH_LIST'
const FETCH_BORROWERS_PASS='FETCH_BORROWERS_PASS'

export {FETCH_LIST,FETCH_LIST_REQUEST,FETCH_LIST_PASS,FETCH_ERROR,FETCH_BORROWERS_PASS,FETCH_BORROWERS_LIST,FETCH_BORROWERS_REQUEST}

