const options = [
    { value: 's1', label: 's1' },
      { value: 's1A', label: 's1A' },
      { value: 's1B', label: 's1B' },
  
      { value: 's2', label: 's2' },
      { value: 's2A', label: 's2A' },
      { value: 's2B', label: 's2B' },
  
      { value: 's3', label: 's3' },
      { value: 's3A', label: 's3A' },
      { value: 's3B', label: 's3B' },
  
      {value:'s4MPC',label:'s4MPC'},
      {value:'s4MPC_A',label:'s4MPC_A'},
      {value:'s4MPC_B',label:'s4MPC_B'},
      {value:'s4MCB',label:'s4MCB'},
      {value:'s4MCB_A',label:'s4MCB_A'},
      {value:'s4MCB_B',label:'s4MCB_B'},
      {value:'s4PCB',label:'s4PCB'},
      {value:'s4PCB_A',label:'s4PCB_A'},
      {value:'s4PCB_B',label:'s4PCB_B'},
      {value:'s4PCM',label:'s4PCM'},
      {value:'s4PCM_A',label:'s4PCM_A'},
      {value:'s4PCM_B',label:'s4PCM_B'},
      {value:'s4PCM',label:'s4PCM'},
      {value:'s4PCM_A',label:'s4PCM_A'},
      {value:'s4PCM_B',label:'s4PCM_B'},
  
      {value:'s5MPC',label:'s5MPC'},
      {value:'s5MPC_A',label:'s5MPC_A'},
      {value:'s5MPC_B',label:'s5MPC_B'},
      {value:'s5MCB',label:'s5MCB'},
      {value:'s5MCB_A',label:'s5MCB_A'},
      {value:'s5MCB_B',label:'s5MCB_B'},
      {value:'s5PCB',label:'s5PCB'},
      {value:'s5PCB_A',label:'s5PCB_A'},
      {value:'s5PCB_B',label:'s5PCB_B'},
      {value:'s5PCM',label:'s5PCM'},
      {value:'s5PCM_A',label:'s5PCM_A'},
      {value:'s5PCM_B',label:'s5PCM_B'},
      {value:'s5PCM',label:'s5PCM'},
      {value:'s5PCM_A',label:'s5PCM_A'},
      {value:'s5PCM_B',label:'s5PCM_B'},
  
      {value:'s6MPC',label:'s6MPC'},
      {value:'s6MPC_A',label:'s6MPC_A'},
      {value:'s6MPC_B',label:'s6MPC_B'},
      {value:'s6MCB',label:'s6MCB'},
      {value:'s6MCB_A',label:'s6MCB_A'},
      {value:'s6MCB_B',label:'s6MCB_B'},
      {value:'s6PCB',label:'s6PCB'},
      {value:'s6PCB_A',label:'s6PCB_A'},
      {value:'s6PCB_B',label:'s6PCB_B'},
      {value:'s6PCM',label:'s6PCM'},
      {value:'s6PCM_A',label:'s6PCM_A'},
      {value:'s6PCM_B',label:'s6PCM_B'},
      {value:'s6PCM',label:'s6PCM'},
      {value:'s6PCM_A',label:'s6PCM_A'},
      {value:'s6PCM_B',label:'s6PCM_B'}
  ] 
 export const optionGender=[{ value: 'M', label: 'Male' },{ value: 'F', label: 'Female' }]
  export default options