const FETCH_LIST_REQUEST='FETCH_LIST_REQUEST_T'
const FETCH_LIST='FETCH_LIST_T'
const FETCH_ERROR='FETCH_ERROR_T'
const FETCH_LIST_PASS='FETCH_LIST_PASS_T'
//BORROWERS DATA
const FETCH_BORROWERS_REQUEST='FETCH_BORROWERS_REQUEST_T'
const FETCH_BORROWERS_LIST='FETCH_LIST_T'
const FETCH_BORROWERS_PASS='FETCH_BORROWERS_PASS_T'

export {FETCH_LIST,FETCH_LIST_REQUEST,FETCH_LIST_PASS,FETCH_ERROR,FETCH_BORROWERS_PASS,FETCH_BORROWERS_LIST,FETCH_BORROWERS_REQUEST}

 