const USER_LOGIN='USER_LOGIN'
const USER_LOGOUT='USER_LOGOUT'
const USER_ERROR='USER_ERROR'
const INVALID_CREDENTIALS='INVALID_CREDENTIALS'

export {USER_LOGIN,USER_LOGOUT,USER_ERROR,INVALID_CREDENTIALS}


